<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AlatUkur;
use Carbon\Carbon;

class AlatUkurSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_alat' => '3MMC001',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo 104 139',
                'sn' => '66360229',
                'spesifikasi' => '0-100 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC002',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo 293-240',
                'sn' => '95100904',
                'spesifikasi' => '0-1 inch',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC003',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo 104 140',
                'sn' => '72452612',
                'spesifikasi' => '0-25 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC005',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo 103 2060',
                'sn' => '1032060',
                'spesifikasi' => '25-50 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC006',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo',
                'sn' => '47128582',
                'spesifikasi' => '50-75 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC007',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo',
                'sn' => '66808595',
                'spesifikasi' => '50-75 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC008',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo',
                'sn' => '47130668',
                'spesifikasi' => '50-75 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC009',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo 103 140 10',
                'sn' => '-',
                'spesifikasi' => '75-100 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC010',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo 103 141 I',
                'sn' => '932038',
                'spesifikasi' => '75-100 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC011',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo 103 143 II',
                'sn' => '-',
                'spesifikasi' => '75-100 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC012',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo',
                'sn' => '80588',
                'spesifikasi' => '75-100 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC013',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo',
                'sn' => 'M70458',
                'spesifikasi' => '75-100 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2024, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2025, 12, 1),
            ],
            [
                'kode_alat' => '3MMC014',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo 103 141',
                'sn' => '-',
                'spesifikasi' => '100-125 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC015',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo 103 141 10',
                'sn' => '65159315',
                'spesifikasi' => '100-125 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC016',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo 103 14210',
                'sn' => '65549441',
                'spesifikasi' => '125-150 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC017',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo 103 143 10',
                'sn' => '37023057',
                'spesifikasi' => '150-175 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC018',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo 104 136',
                'sn' => '64141579',
                'spesifikasi' => '150-300 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC019',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo 104 137',
                'sn' => '70015928',
                'spesifikasi' => '150-300 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC020',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo',
                'sn' => '57008000',
                'spesifikasi' => '175-200 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
            [
                'kode_alat' => '3MMC021',
                'nama_alat' => 'Outside Micrometer',
                'merk' => 'Mitutoyo',
                'sn' => '52005595',
                'spesifikasi' => '300-400 mm',
                'kondisi' => 'Baik',
                'tanggal_kalibrasi_terakhir' => Carbon::create(2025, 11, 1),
                'tanggal_kalibrasi_selanjutnya' => Carbon::create(2026, 12, 1),
            ],
        ];

        foreach ($data as $item) {
            AlatUkur::firstOrCreate(['kode_alat' => $item['kode_alat']], $item);
        }
    }
}